### ISSUE TITLE
Unable to run the repo locally.

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/guides#140]
After running `yarn install` and running `yarn run dev` I am getting this in the terminal:
Is it with me or everyone else:
```
yarn run v0.27.5
$ node seed && gatsby develop
/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Error: ENOTDIR: not a directory, scandir '/home/invinciblycool/FCC/guides/src/pages/articles/sql/sql-alter-table/'
    at AnonymousObserver.listAllDirs.toArray.subscribe.err [as _onError] (/home/invinciblycool/FCC/guides/seed/_createNavData.js:50:15)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.tryCatcher (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:2501:59)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.tryCatcher (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:5891:52)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Bouncey** [comment]
Thanks for the issue @invinciblycool, I have incorporated a fix in #129 which should be merged shortly
