### ISSUE TITLE
"yarn run dev" fails

### ISSUE THREAD

**Issue by davcri** [freeCodeCamp/guides#204]
`yarn run dev` command fails.  
I followed the instructions provided in the README [(Running the guide locally)](https://github.com/freeCodeCamp/guides#running-the-guide-locally-on-your-own-computer).

- Complete command log: [log.txt](https://github.com/freeCodeCamp/guides/files/1254190/log.txt)  
- **OS**: Arch Linux, **yarn**: v0.277.5
- Relevant output:
``` bash
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch /mnt/Data/programming_workspace/projects/guide-clean/node_modules/jspm-npm/test/fixtures ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/mnt/Data/programming_workspace/projects/guide-clean/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
```

**Comment by invinciblycool** [comment]
You might want to run `yarn install` before `yarn run dev`.

**Comment by systimotic** [comment]
Hi @davcri! Thank you for your interest in this project.

From the full output, I can see that you have already run `yarn install` successfully.

I did a google search for the error: `ENOSPC`. It brought up some suggested fixes, related to the system of the user. It either means your hard drive is out of space, or something I don't quite understand that can be fixed by following the instructions here: https://stackoverflow.com/a/32600959

Can you try that out and tell us if it helped?

**Comment by Bouncey** [comment]
@davcri I have just had the same issue when working on a different system. 

The steps provided in the SO article that @systimotic linked to worked for me.

I am going to close this issue as I'm sure it is not an issue with this project. If you continue to experience problems, it will either be your hardware or a memory leak in the gatsby build process maybe?

Feel free to add any further info to this thread, if it turns out it is a problem with this repo, please reopen this issue

Happy coding :sparkles: :sparkles:

**Comment by davcri** [comment]
Fixed, thank you guys for your help 😄 

The problem was in fact the OS limiting the number of watchers.  
A temporary fix is to double this number:

``` bash
sudo sysctl fs.inotify.max_user_watches=16384
```

To make this fix persistent across reboots, there are instructions in the stackoverflow thread.

**Comment by systimotic** [comment]
I'm glad you figured it out @davcri!
