### ISSUE TITLE
Deploy previews failing: can't find module 'parse-passwd'

### ISSUE THREAD

**Issue by 1andee** [freeCodeCamp/guides#7896]
Reference PRs https://github.com/freeCodeCamp/guides/pull/2587 and https://github.com/freeCodeCamp/guides/pull/7691, the below error is being thrown during deploy preview:

```
2:12:00 PM: NPM modules installed using Yarn
2:12:00 PM: yarn run v1.3.2
2:12:00 PM: $ node bin/createNavData && node --max_old_space_size=7168 ./node_modules/gatsby/dist/gatsby-cli.js build
2:12:01 PM: Creating navData...
2:12:01 PM: navData created
2:12:01 PM: It took 381ms to create the navData for 2533 pages
2:12:02 PM: A local install of Gatsby exists but failed to load.
2:12:02 PM: { Error: Cannot find module 'parse-passwd'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/build/repo/node_modules/homedir-polyfill/index.js:5:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/build/repo/node_modules/global-prefix/index.js:10:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32) code: 'MODULE_NOT_FOUND' }
```

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Bouncey** [comment]
Please do not merge PR's when not all checks have passed. As soon as a PR is merged, it goes to production. If we don't have a green test suite then something is wrong and we need to investigate. 

There was an issue with the build environment which in now resolved.
